### ISSUE TITLE
plugin.yaml 中的 Logo 配置方式可能导致在未启用插件时无法加载

### ISSUE THREAD

**Issue by ruibaby** [LIlGG/plugin-live2d#1]
https://github.com/LIlGG/plugin-live2d/blob/main/src/main/resources/plugin.yaml#L12

可以将 logo.gif 放在 resources 根目录，然后 `spec.logo` 写为 `logo.gif` 既可。

**Comment by LIlGG** [comment]
close #2  等待 https://github.com/halo-dev/halo/pull/2940 修复完成即可正常使用
