### ISSUE TITLE
OpenAI 代理设置不生效

### ISSUE THREAD

**Issue by wan92hen** [LIlGG/plugin-live2d#13]
配置代理后未生效，实际未使用代理。

https://github.com/LIlGG/plugin-live2d/blob/88ddd633a8da2fab6e0d8ab6af276859c482034f/src/main/java/run/halo/live2d/openai/service/impl/OpenAIServiceImpl.java#L84-L93

**Comment by LIlGG** [comment]
当前确实没有生效，计划修复。
