### ISSUE TITLE
关于模型的尺寸调整及聊天框的大小调整

### ISSUE THREAD

**Issue by Payne-Wang** [LIlGG/plugin-live2d#16]
请问模型和聊天框的尺寸可以调整吗？或者可以设置透明度？模型太大有时候会挡住页面的内容。ps: openai的接口真的好用！谢谢！

**Comment by LIlGG** [comment]
感谢！目前提供了看板娘位置的选项，可以将看板娘移动到左侧。
目前没有模型和聊天框尺寸的自定义设置，你可以通过自定义 css 来实现，将自定义 css 使用 Halo 的代码注入功能注入即可。例如：

```
<style>
#live2d {
 width: 200px;
 height: 200px;
}

# live2d-tips {
  width: 200px;
}
</style>
```

**Comment by Payne-Wang** [comment]
感谢，给的代码很好用，问题完美解决

**Comment by DeliciousYellow** [comment]
感谢

**Comment by DeliciousYellow** [comment]
我实测用 https://github.com/LIlGG/plugin-live2d/issues/16#issuecomment-1541796522 回答的样式无效。
使用 !important 提高优先级后生效。
`<style>
#live2d {
 width: 150px !important;
 height: 150px !important;
}`
`# live2d-tips {
  width: 150px !important;
}
</style>`

我的Halo版本2.21.1
我的看板娘版本1.2.2
