### ISSUE TITLE
OpenAI无法设置

### ISSUE THREAD

**Issue by ikechan8370** [LIlGG/plugin-live2d#17]
OpenAI设置开启后会变成如图这样
<img width="745" alt="image" src="https://github.com/LIlGG/plugin-live2d/assets/21212372/87a86e75-a5b5-43f8-ad86-c642e38b41bb">
卸载重装依旧是这样

**Comment by LIlGG** [comment]
根据你的描述，没法推断出你的问题原因。 

但你可以试试在插件列表中，选择 `重置` 来解决问题。

**Comment by ikechan8370** [comment]
谢谢。重置试过了。
不过刚刚把halo本体从2.4.0升级到2.6就正常显示了。虽然不太清楚原因
