### ISSUE TITLE
请问如何快速查看不同模型和材质的编号？

### ISSUE THREAD

**Issue by E9C50** [LIlGG/plugin-live2d#22]
想要设置默认模型，但是手动一个个切换加载很慢，是否有对应关系预览或者其他方式？另外材质是什么东西，第一次用这个不太了解

**Comment by LIlGG** [comment]
模型和材质归属于 API 所有，本仓库无法得知对应的模型和材质。默认提供的 API 为第三方的，因此无法得知。
你可以将模型理解为人物模型，而材质你可以理解为人物的衣服。
