### ISSUE TITLE
openai设置apikey和自己的云代理函数但是不生效问题

### ISSUE THREAD

**Issue by xiaokai06** [LIlGG/plugin-live2d#25]
<img width="1661" alt="image" src="https://github.com/LIlGG/plugin-live2d/assets/37428940/30ad6a44-9f24-4e2a-84c2-6db2cd26b35b">
<img width="1679" alt="image" src="https://github.com/LIlGG/plugin-live2d/assets/37428940/0199225b-a14e-402d-83dc-5ccf93bd7671">

**Comment by xiaokai06** [comment]
请大佬帮忙指导一下是什么原因

**Comment by LIlGG** [comment]
一个已知问题，目前 baseURL 没有能够生效，查看 https://github.com/LIlGG/plugin-live2d/issues/19 ，已修复，但需要待 #20  完成之后发布一个新版本来解决这个问题。

**Comment by xiaokai06** [comment]
好的

**Comment by xiaokai06** [comment]
你好博主，请问咱们有无技术沟通的交流群，能否申请加入交流

**Comment by LIlGG** [comment]
目前没有交流群

**Comment by LIlGG** [comment]
已发布 v1.1.2 版本。
