### ISSUE TITLE
Open Ai接口的问题

### ISSUE THREAD

**Issue by NikoYomi** [LIlGG/plugin-live2d#28]
想请问下怎么对接Open Ai，小白正在学习中！

**Comment by LIlGG** [comment]
抱歉回复的较晚。一般来说只需要具有 openai-key 即可，随后在插件设置中配置就可以。
如果是代码层面的话，可以参考 https://github.com/LIlGG/plugin-live2d/tree/main/src/main/java/run/halo/live2d/openai

**Comment by NikoYomi** [comment]
> 抱歉回复的较晚。一般来说只需要具有 openai-key 即可，随后在插件设置中配置就可以。 如果是代码层面的话，可以参考 https://github.com/LIlGG/plugin-live2d/tree/main/src/main/java/run/halo/live2d/openai

感谢回复！openai-key设置没问题，但是总是报错说接口问题。很奇怪找不到具体在哪，代理也换了很多个也没解决.

**Comment by LIlGG** [comment]
> 感谢回复！openai-key设置没问题，但是总是报错说接口问题。很奇怪找不到具体在哪，代理也换了很多个也没解决.

方便贴一下 Halo 后端日志吗？

**Comment by NikoYomi** [comment]
> 

感谢你提到日志这个关键信息，我才发现好像是我的费用用完了。/(ㄒoㄒ)/~~

**Comment by JCVICTORSUN** [comment]
> 抱歉回复的较晚。一般来说只需要具有 openai-key 即可，随后在插件设置中配置就可以。 如果是代码层面的话，可以参考 https://github.com/LIlGG/plugin-live2d/tree/main/src/main/java/run/halo/live2d/openai

请问API_BASE_URL怎么设置哇，我查了官方文档找到了个这个
https://api.openai.com/v1/chat/completions

**Comment by LIlGG** [comment]
> 

BaseURL 代表调用 OpenAi 接口的地址，可以不设置，默认为 `https://api.openai.com` 是官方的地址。但大陆地区访问可能会无法访问，此时就需要使用代理或者其他方式来更改这个地址用于访问。

**Comment by LIlGG** [comment]
> > 抱歉回复的较晚。一般来说只需要具有 openai-key 即可，随后在插件设置中配置就可以。 如果是代码层面的话，可以参考 https://github.com/LIlGG/plugin-live2d/tree/main/src/main/java/run/halo/live2d/openai
> 
> 请问API_BASE_URL怎么设置哇，我查了官方文档找到了个这个 https://api.openai.com/v1/chat/completions

BaseURL 代表调用 OpenAi 接口的地址，可以不设置，默认为 https://api.openai.com 是官方的地址。但大陆地区访问可能会超时或无法访问，此时就需要使用代理或者其他方式来更改这个地址用于访问。

**Comment by yanpengfei-git** [comment]
> > > 抱歉回复的较晚。一般来说只需要具有 openai-key 即可，随后在插件设置中配置就可以。 如果是代码层面的话，可以参考 https://github.com/LIlGG/plugin-live2d/tree/main/src/main/java/run/halo/live2d/openai
> > 
> > 
> > 请问API_BASE_URL怎么设置哇，我查了官方文档找到了个这个 https://api.openai.com/v1/chat/completions
> 
> BaseURL 代表调用 OpenAi 接口的地址，可以不设置，默认为 https://api.openai.com 是官方的地址。但大陆地区访问可能会超时或无法访问，此时就需要使用代理或者其他方式来更改这个地址用于访问。

我的是香港服务器，在终端中可以ping通官方接口，但是配置好key后，页面对话报错
<img width="1426" alt="image" src="https://github.com/LIlGG/plugin-live2d/assets/37141737/a1897768-f3c4-4cbe-ad12-d4f50ac74cb4">
<img width="1436" alt="image" src="https://github.com/LIlGG/plugin-live2d/assets/37141737/1f95a409-bd0b-4bf6-82ab-23de067371d9">
