### ISSUE TITLE
启用插件后服务器 500

### ISSUE THREAD

**Issue by lvtenghui** [LIlGG/plugin-live2d#3]
![image](https://user-images.githubusercontent.com/50571783/207508451-34be8708-ab33-41c9-8b6e-a37cb7ba7e59.png)
 HALO 2.0
主题：HAO1.0.3 与 Sakura2.0.0 均会报错

**Comment by lvtenghui** [comment]
实测是 API接口 问题，换到
 https://live2d.fghrsh.net/api/ 后无报错

**Comment by LIlGG** [comment]
> 实测是 API接口 问题，换到 https://live2d.fghrsh.net/api/ 后无报错

与接口应当无关，接口的报错不会影响到 Halo 500 错误。插件初次安装时，会出现无法读取到插件配置文件的问题，这个可能是 Halo 读取配置文件的问题。进而导致获取参数出错，报错 NEP 问题。计划发布 1.0.1 来修复这个问题。目前代码已经提交。
https://github.com/LIlGG/plugin-live2d/commit/ea80f41e21f1593b5131246347efc20e54453920

**Comment by LIlGG** [comment]
另外重启 Halo 也可解决这个问题

**Comment by lvtenghui** [comment]
> 

是的，重启解决这个问题了，但模型好像无法切换，输完模型编号后保存无变化

**Comment by LIlGG** [comment]
> > 
> 
> 是的，重启解决这个问题了，但模型好像无法切换，输完模型编号后保存无变化

输入的模型是默认模型。只会在首次进入网站时生效。如果已经进入过网站，那么之前的模型编号会存在 `localstore` 内。想切换模型可以通过右侧工具栏来进行切换

**Comment by LIlGG** [comment]
[v1.0.1](https://github.com/LIlGG/plugin-live2d/releases/tag/v1.0.1) 版本已经发布，这个 issue 我关闭了哈，有其他问题可以再新建 issue
