### ISSUE TITLE
希望增加优先后台配置模型id和纹理id

### ISSUE THREAD

**Issue by stars-one** [LIlGG/plugin-live2d#33]
我修改了模型id和材质的id,但是实际上页面加载js控制台里的url还是固定为1-53

![image](https://github.com/LIlGG/plugin-live2d/assets/31400169/ef228284-f95e-4228-8694-4342e44f7fc2)

接口地址我是换成了`https://live2d.fghrsh.net/api/`

清除缓存都试过了,没有效果

**Comment by stars-one** [comment]
确认了,是缓存问题导致

**Comment by stars-one** [comment]
不过话说这个缓存问题的话可以优化一下吗?不能说我后台改了配置,前端得清个缓存才不生效吧?觉得体验有点不好,不应该是优先后台配置嘛?

现在存储到前端的,我知道就是为了保存前端其他用户访问的时候点了换装,然后下次进来还是同样的模型

**考虑可以在配置加个开关,如果开启,就是强制使用后台配置的模型id和材质,忽略前台用户的设置**

**Comment by LIlGG** [comment]
我的解决方案是更倾向于缓存中保存上一次的配置信息，如果发现配置信息发生了变动，则清理缓存，如果配置信息不变，则继续保持原有的逻辑。
