### ISSUE TITLE
2.10版本 插件1.1.3 类加载错误

### ISSUE THREAD

**Issue by shanzhengfei** [LIlGG/plugin-live2d#35]
场景：halo 2.8 导出备份（用的是live2d 1.1.3 对话无问题），删除2.8 容器，重新下载2.10 docker安装部署，启动后导入2.8的备份。看板娘开启对话，首页和看板娘对话，后台报错，看起来应该是类加载器冲突
![image](https://github.com/LIlGG/plugin-live2d/assets/41267902/d2a87692-2bfa-4686-97d1-bbbc4b5ec35d)
![image](https://github.com/LIlGG/plugin-live2d/assets/41267902/a9a73b91-11eb-4bb2-b1a1-fc7e1603cdef)
![image](https://github.com/LIlGG/plugin-live2d/assets/41267902/b3215779-5351-4728-b444-d8f86b064190)

**Comment by huangjiachenge** [comment]
+1

**Comment by huangjiachenge** [comment]
2023-12-07T12:43:52.264+08:00  WARN 7 --- [ctor-http-nio-1] reactor.core.Exceptions                  : throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
halo  | 
halo  | java.lang.LinkageError: loader constraint violation: when resolving method 'reactor.core.publisher.Flux reactor.core.publisher.Flux.from(org.reactivestreams.Publisher)' the class loader org.pf4j.PluginClassLoader @1fa996a of the current class, run/halo/live2d/openai/OpenAiController, and the class loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27 for the method's defining class, reactor/core/publisher/Flux, have different Class objects for the type org/reactivestreams/Publisher used in the signature (run.halo.live2d.openai.OpenAiController is in unnamed module of loader org.pf4j.PluginClassLoader @1fa996a, parent loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27; reactor.core.publisher.Flux is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27, parent loader 'app')
halo  | 	at run.halo.live2d.openai.OpenAiController.chatProcess(OpenAiController.java:49) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo  | 	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:145) ~[spring-webflux-6.0.13.jar:6.0.13]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:293) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:474) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:481) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:273) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.request(FluxReceive.java:131) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2041) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2025) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:171) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:170) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:148) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | 
halo  | 2023-12-07T12:43:52.283+08:00  WARN 7 --- [ctor-http-nio-1] reactor.core.Exceptions                  : throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
halo  | 
halo  | java.lang.LinkageError: loader constraint violation: when resolving method 'reactor.core.publisher.Flux reactor.core.publisher.Flux.from(org.reactivestreams.Publisher)' the class loader org.pf4j.PluginClassLoader @1fa996a of the current class, run/halo/live2d/openai/OpenAiController, and the class loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27 for the method's defining class, reactor/core/publisher/Flux, have different Class objects for the type org/reactivestreams/Publisher used in the signature (run.halo.live2d.openai.OpenAiController is in unnamed module of loader org.pf4j.PluginClassLoader @1fa996a, parent loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27; reactor.core.publisher.Flux is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27, parent loader 'app')
halo  | 	at run.halo.live2d.openai.OpenAiController.chatProcess(OpenAiController.java:49) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo  | 	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:145) ~[spring-webflux-6.0.13.jar:6.0.13]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:293) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:474) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:481) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:273) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.request(FluxReceive.java:131) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2041) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2025) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:171) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:170) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:148) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | 
halo  | 2023-12-07T12:43:52.311+08:00  WARN 7 --- [ctor-http-nio-1] i.n.u.concurrent.AbstractEventExecutor   : A task raised an exception. Task: reactor.netty.channel.FluxReceive$$Lambda$2863/0x9a56b700@d561be
halo  | 
halo  | java.lang.LinkageError: loader constraint violation: when resolving method 'reactor.core.publisher.Flux reactor.core.publisher.Flux.from(org.reactivestreams.Publisher)' the class loader org.pf4j.PluginClassLoader @1fa996a of the current class, run/halo/live2d/openai/OpenAiController, and the class loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27 for the method's defining class, reactor/core/publisher/Flux, have different Class objects for the type org/reactivestreams/Publisher used in the signature (run.halo.live2d.openai.OpenAiController is in unnamed module of loader org.pf4j.PluginClassLoader @1fa996a, parent loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27; reactor.core.publisher.Flux is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @7aac27, parent loader 'app')
halo  | 	at run.halo.live2d.openai.OpenAiController.chatProcess(OpenAiController.java:49) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo  | 	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:145) ~[spring-webflux-6.0.13.jar:6.0.13]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:293) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:474) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:481) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:273) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.request(FluxReceive.java:131) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2041) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2025) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:171) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.11.jar:3.5.11]
halo  | 	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:170) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at reactor.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:148) ~[reactor-netty-core-1.1.12.jar:1.1.12]
halo  | 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

**Comment by JoyBoy521** [comment]
解决了吗， 作者 这该怎么办啊

**Comment by JoyBoy521** [comment]
难道要降低版本吗

**Comment by LIlGG** [comment]
> 解决了吗， 作者 这该怎么办啊

目前还没有太多的时间和精力来维护此插件，这周末我会抽空来修复一下这个问题。

**Comment by JoyBoy521** [comment]
> > 解决了吗， 作者 这该怎么办啊
> 
> 目前还没有太多的时间和精力来维护此插件，这周末我会抽空来修复一下这个问题。

手机端 你准备添加吗

**Comment by JoyBoy521** [comment]
> > 解决了吗， 作者 这该怎么办啊
> 
> 目前还没有太多的时间和精力来维护此插件，这周末我会抽空来修复一下这个问题。

谢谢作者  爱死你了
