### ISSUE TITLE
无法响应鼠标移入事件

### ISSUE THREAD

**Issue by Miraclezhb** [LIlGG/plugin-live2d#5]
我安装看板娘插件后，自己配置了鼠标移入的响应事件。但是鼠标移入至/tags 或者 /categories 时，没有做出相关的响应。/about 页面的响应是正常的，是和主题不兼容吗？我使用的主题是 sakura

**Comment by LIlGG** [comment]
能否提供一下你配置的鼠标移入响应事件的配置？

**Comment by LIlGG** [comment]
> tags

使用的是第三种全量自定义 TIPS 文件的方式吗？

**Comment by Miraclezhb** [comment]
对的

**Comment by LIlGG** [comment]
> 对的

我验证一下，感谢提供的信息。

**Comment by Miraclezhb** [comment]
好的，也感谢大佬这么及时的回复

**Comment by LIlGG** [comment]
> 好的，也感谢大佬这么及时的回复

经过测试 categories 和 tags 都能正常触发，如下图

![image](https://user-images.githubusercontent.com/31335418/210756334-f50d28c3-37f1-4bb2-a7b0-ead7b5ccb8b0.png)

**Comment by Miraclezhb** [comment]
> > 好的，也感谢大佬这么及时的回复
> 
> 经过测试 categories 和 tags 都能正常触发，如下图
> 
> ![image](https://user-images.githubusercontent.com/31335418/210756334-f50d28c3-37f1-4bb2-a7b0-ead7b5ccb8b0.png)

啊？跟我的配置一样吗？

**Comment by LIlGG** [comment]
> 啊？跟我的配置一样吗？

是的，也添加了和你相同的其他文本，比如 novels。

![image](https://user-images.githubusercontent.com/31335418/210758181-c1997ea9-7400-44e0-88c7-5f9663e34f25.png)

**Comment by LIlGG** [comment]
有一种可能或许是由于 Halo 插件配置文件加载的原因，你的插件如果是新安装的，建议重启一下 Halo 试试。有可能是配置文件没有加载成功，导致 Live2d 读取了默认的 tips 文件

**Comment by Miraclezhb** [comment]
> 有一种可能或许是由于 Halo 插件配置文件加载的原因，你的插件如果是新安装的，建议重启一下 Halo 试试。有可能是配置文件没有加载成功，导致 Live2d 读取了默认的 tips 文件

奥，我试试

**Comment by Miraclezhb** [comment]
确实可能是没读取到配置文件，重启之后都正常了

**Comment by LIlGG** [comment]
> 确实可能是没读取到配置文件，重启之后都正常了

ok，问题已解决，此 issue 关闭，如果还有其他问题可以新建 issue
