### ISSUE TITLE
右侧工具栏不显示 更换模型api也无效果

### ISSUE THREAD

**Issue by RockRockWhite** [LIlGG/plugin-live2d#6]
> 插件版本号：1.0.1
> 主题：Sakura 2.0.0
> Holo版本号：v2.1.0

是因为插件还没有完全完成吗？

![image](https://user-images.githubusercontent.com/37936279/215272435-3187d8bc-b713-4a4c-8965-40b584657318.png)

**Comment by LIlGG** [comment]
该问题是由于 halo 插件初始化时无法找到默认值，因此进行了回退导致的。 该问题已在 Halo 2.2 版本中修复，详情可以查看 https://github.com/halo-dev/halo/issues/3160
