### ISSUE TITLE
右侧小工具重复出现的问题

### ISSUE THREAD

**Issue by Miraclezhb** [LIlGG/plugin-live2d#8]
![image](https://user-images.githubusercontent.com/65268506/226533383-166525bc-9739-41cd-a9d6-96d060ed034c.png)
当我取消了几个右侧小工具时，它就会重复显示几个图标

**Comment by LIlGG** [comment]
我本地没有复现这个问题，希望能够提供更多的信息。比如进行了哪些操作，或者 `F12` 打开控制台，查看一下报错信息。

**Comment by LIlGG** [comment]
太久没有响应，此 issue 关闭，如有问题可重新打开。
